export const FETCH_IDEAS = 'FETCH_IDEAS'
export const NEW_IDEA = 'NEW_IDEA'
export const SAVED_IDEAS = 'SAVED_IDEAS'
export const USER_IDEAS = 'USER_IDEAS'
export const CURRENT_USER = 'CURRENT_USER'
export const NEW_USER = 'NEW_USER'
export const ALL_USERS = 'ALL_USERS'
